# Generated by Django 4.2 on 2026-04-15 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='server-1', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_navigation_config',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MenuPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_patches', to='user.navigationconfig')),
            ],
            options={
                'db_table': 'user_menu_patch',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_extra_items', to='user.navigationconfig')),
            ],
            options={
                'db_table': 'user_menu_extra_item',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExtraRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=128, unique=True)),
                ('path', models.CharField(max_length=255)),
                ('component_key', models.CharField(max_length=128)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_routes', to='user.navigationconfig')),
            ],
            options={
                'db_table': 'user_extra_route',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
