# Generated by Django 4.2 on 2026-04-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraroute',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='留空表示所有用户可访问；设置后仅这些用户组可访问。', related_name='navigation_extra_routes', to='auth.group'),
        ),
        migrations.AddField(
            model_name='menuextraitem',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='留空表示所有用户可见；设置后仅这些用户组可见。', related_name='navigation_menu_extra_items', to='auth.group'),
        ),
    ]
