# Generated by Django 4.2.20 on 2025-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAccessoryTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(verbose_name='车辆 ID')),
                ('accessory_name', models.CharField(max_length=255, verbose_name='配件名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='配件价格')),
            ],
            options={
                'verbose_name': '车辆配件',
                'verbose_name_plural': '车辆配件',
            },
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255, verbose_name='车辆名称')),
                ('year', models.IntegerField(verbose_name='生产年份')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='车辆价格')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='介绍 & 备注')),
            ],
            options={
                'verbose_name': '车辆信息',
                'verbose_name_plural': '车辆信息',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypeTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(verbose_name='车辆 ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='车辆类型名称')),
            ],
            options={
                'verbose_name': '车辆类型',
                'verbose_name_plural': '车辆类型',
            },
        ),
    ]
