# Generated by Django 4.2.20 on 2025-06-12 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_vehicleaccessorytab_vehicle_accessory_tab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_accessory_tab',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='vehicle_accessory_tab',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.vehicle_info', verbose_name='车辆'),
            preserve_default=False,
        ),
    ]
