# Generated by Django 4.2.20 on 2025-06-12 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_vehicle_accessory_tab_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_accessory_tab',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='car.vehicle_info', verbose_name='车辆'),
        ),
    ]
