# Generated by Django 4.2.20 on 2025-06-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleAccessoryTab',
            new_name='vehicle_accessory_tab',
        ),
        migrations.RenameModel(
            old_name='VehicleInfo',
            new_name='vehicle_info',
        ),
        migrations.RenameModel(
            old_name='VehicleTypeTab',
            new_name='vehicle_type_tab',
        ),
    ]
